mobileData = [{
        name: `iphone 11`,
        release_year: 2019,
        brand: `apple`,
        version: 64,
        price: `21.990.000 vnd`,
        specs: {
            screen: 6.1,
            screen_type: `ips lcd`,
            os: `ios 13`,
            main_camera: `12 mp`,
            fron_camera: `12 mp`,
            cpu: `apple a13 bionic 6 core`,
            ram: `4 gb`,
            rom: `64 gb`,
            battery: `3110 mAh`,
            sim: `1 esim & 1 nano sim`,
        }
    }, {
        name: `Xiaomi Redmi 9`,
        release_year: 2019,
        brand: `xiaomi`,
        version: 64,
        price: `3.990.000 vn₫`,
        specs: {
            screen: 6.1,
            screen_type: `ips lcd`,
            os: `ios 13`,
            main_camera: `12 mp`,
            fron_camera: `12 mp`,
            cpu: `apple a13 bionic 6 core`,
            ram: `4 gb`,
            rom: `64 gb`,
            battery: `3110 mAh`,
            sim: `1 esim & 1 nano sim`,
        }
    },
    {
        name: `iphone 11`,
        release_year: 2019,
        brand: `apple`,
        version: 64,
        price: 21990000,
        specs: {
            screen: 6.1,
            screen_type: `ips lcd`,
            os: `ios 13`,
            main_camera: `12 mp`,
            fron_camera: `12 mp`,
            cpu: `apple a13 bionic 6 core`,
            ram: `4 gb`,
            rom: `64 gb`,
            battery: `3110 mAh`,
            sim: `1 esim & 1 nano sim`,
        }
    },
    {
        name: `iphone 11`,
        release_year: 2019,
        brand: `apple`,
        version: 64,
        price: 21990000,
        specs: {
            screen: 6.1,
            screen_type: `ips lcd`,
            os: `ios 13`,
            main_camera: `12 mp`,
            fron_camera: `12 mp`,
            cpu: `apple a13 bionic 6 core`,
            ram: `4 gb`,
            rom: `64 gb`,
            battery: `3110 mAh`,
            sim: `1 esim & 1 nano sim`,
        }
    },
    {
        name: `iphone 11`,
        release_year: 2019,
        brand: `apple`,
        version: 64,
        price: 21990000,
        specs: {
            screen: 6.1,
            screen_type: `ips lcd`,
            os: `ios 13`,
            main_camera: `12 mp`,
            fron_camera: `12 mp`,
            cpu: `apple a13 bionic 6 core`,
            ram: `4 gb`,
            rom: `64 gb`,
            battery: `3110 mAh`,
            sim: `1 esim & 1 nano sim`,
        }
    },
]