console.log(`What result in boolean`);
console.log('Boolean(10) is ' + Boolean(10)); 
console.log('<br>'); 
console.log('Boolean("GeeksforGeeks") is ' + Boolean("GeeksforGeeks")); 
console.log('<br>'); 
console.log('Boolean(2.74) is ' + Boolean(2.74)); 
console.log('<br>'); 
console.log('Boolean(-1) is ' + Boolean(-1)); 
console.log('<br>'); 
console.log("Boolean('true') is " + Boolean('true')); 
console.log('<br>'); 
console.log("Boolean('false') is " + Boolean('false')); 
console.log('<br>'); 
console.log('Boolean(3 * 2 + 1.11) is ' + Boolean(3 * 2 + 1.11)); 
console.log('<br>'); 
console.log('Boolean(1<2) is ' + Boolean(1 < 2)); 